name: keylol action
on: push

jobs:
  gitmand:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: test
        uses: yuyinws/gitmand@master
